# Generated by Django 3.2.6 on 2021-09-13 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_auto_20210913_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
